#!/bin/bash
# set permissions on a directory
#based on https://github.com/jupyter/docker-stacks/blob/master/base-notebook/fix-permissions

set -e

for d in "$@"; do
    find "$d" \
        ! \( \
            -group $GAM_GID \
            -a -perm -g+rwX  \
        \) \
        -exec chgrp $GAM_GID {} \; \
        -exec chmod g+rwX {} \;
    # setuid, setgid *on directories only*
    find "$d" \
        \( \
            -type d \
            -a ! -perm -6000  \
        \) \
        -exec chmod +6000 {} \;
done